remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: ""
url: "https://timin8er.github.io"
title: Timin8er.com
description: Tim Polnow's Profolio
